[build]
  # Diretório de publicação (raiz do projeto)
  publish = "."
  
  # Comando de build (não necessário para HTML estático)
  command = ""

# Configurações de redirecionamento
[[redirects]]
  # Redireciona a raiz para o arquivo HTML principal
  from = "/"
  to = "/9forlives-page.html"
  status = 200

[[redirects]]
  # Redireciona index.html para o arquivo principal
  from = "/index.html"
  to = "/9forlives-page.html"
  status = 301

# Headers de segurança e performance
[[headers]]
  for = "/*"
  [headers.values]
    # Segurança
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance e cache
    Cache-Control = "public, max-age=31536000, immutable"
    
    # HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Headers específicos para HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers para assets estáticos
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações de ambiente
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"